<?php
/* This file was automatically generated by the `grunt public-cachebuster` command (Fri Nov 10 2017 19:15:58 GMT+0000 (UTC)). */
return array(
	'public/dist/admin.js' => '8108f13a77ecb9099cf694f31de4c77d',
	'public/dist/widget.js' => '3f6d15c5086abb4260e5fd930996da56',
	'public/dist/admin.css' => 'f8a2754f629a2c9d93496624d844addc',
	'public/dev/admin.js' => '7312cadf5e13f9a37e8318fa8bc0a134',
	'public/dev/widget.js' => '121457e5292084cdc3d2adbe0f23d56c',
	'public/dev/admin.css' => 'dba5755281df809f4cbb10ae5f72ce16',
);
