<?php
/* This file was automatically generated by the `grunt public-cachebuster` command (Sun Nov 12 2017 15:00:12 GMT+0000 (UTC)). */
return array(
	'public/dist/admin.js' => '100e0d170a5a14ffaec24631767e1597',
	'public/dist/widget.js' => '6a13e770bb9f94f1409a1400601274a2',
	'public/dist/admin.css' => 'f8a2754f629a2c9d93496624d844addc',
	'public/dist/widget.css' => 'd43204352e1435ec351917cc4a169a4c',
	'public/dev/admin.js' => '5a6b587b60ae2f1b0f47f2261baa5979',
	'public/dev/widget.js' => '57cc7f175af0e319e159e57e0ddf22cb',
	'public/dev/admin.css' => 'dba5755281df809f4cbb10ae5f72ce16',
	'public/dev/widget.css' => '5b547261416a8c2e25cb29b50df82e54',
);
