<?php
/* This file was automatically generated by the `grunt public-cachebuster` command (Sat Nov 11 2017 16:45:03 GMT+0000 (UTC)). */
return array(
	'public/dist/admin.js' => '901bbab8e535e9dcc245031122595066',
	'public/dist/widget.js' => '3f6d15c5086abb4260e5fd930996da56',
	'public/dist/admin.css' => 'f8a2754f629a2c9d93496624d844addc',
	'public/dev/admin.js' => '5a6b587b60ae2f1b0f47f2261baa5979',
	'public/dev/widget.js' => '121457e5292084cdc3d2adbe0f23d56c',
	'public/dev/admin.css' => 'dba5755281df809f4cbb10ae5f72ce16',
);
